### PR TITLE
asv_runner 0.2.1

### PR DESCRIPTION
**Pull request by xhochy**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by xhochy** [comment]
Depends on https://github.com/airspeed-velocity/asv_runner/issues/40

**Comment by HaoZeke** [comment]
Just added the source distribution, a re-run should fix the build. Thanks @xhochy

**Comment by mattip** [comment]
When you update the version, you need to update the sha256, it should be `945dd301a06fa9102f221b1e9ddd048f5ecd863796d4c8cd487f5577fe0db66d` [here](https://github.com/conda-forge/asv_runner-feedstock/pull/5/files#diff-f3725a55bf339595bf865fec73bda8ac99f283b0810c205442021f29c06eea9aR10)

**Comment by mattip** [comment]
Import [is failing](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=879374&view=logs&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=986b1512-c876-5f92-0d81-ba851554a0a3&l=702) with 
```
asv-runner 0.2.1 requires importlib-metadata, which is not installed.
```

**Comment by mattip** [comment]
Looking at [the `pyproject.toml`](https://github.com/airspeed-velocity/asv_runner/blob/9b7a26f8d24d91a0cf040b367d1a37f680f01bbd/pyproject.toml#L26), the only hard dependency seems to be `importlib-metadata`

**Pull request merged**
